name: Build 🛠️

on:
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Format + Clippy
        run: |
          cargo fmt --all -- --check
          cargo clippy -- -D warnings --allow dead_code

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Ruff
        run: uv run ruff check --select I .

      - name: Build Rust application
        run: maturin develop --uv --release

      - name: Pytest & Coverage
        run: |
          uv run pytest --durations=10

      - name: Minimize uv cache
        run: uv cache prune --ci
