name: Release 📦

on:
  push:
    tags:
      - "v*.*.*" # Triggers workflow only when a tag matching this pattern is pushed

jobs:
  build-and-publish:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: "Install uv"
        uses: astral-sh/setup-uv@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: "Build"
        run: uv build

      - name: "Publish to Test PyPi"
        run: uv publish --publish-url https://test.pypi.org/legacy/ --token ... --trusted-publishing

      - name: "Verify"
        run: uv run --with litebook --no-project -- python -c "import litebook"
