name: Release 📦

on:
  push:
    tags:
      - "v*.*.*" # Triggers workflow only when a tag matching this pattern is pushed

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        target: [x86, x64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - if: matrix.python-version == '3.13'
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          architecture: ${{ matrix.target }}

      - name: Build Wheels
        uses: PyO3/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        with:
          command: publish
          target: ${{ matrix.target }}
          args: -i ${{ matrix.python-version }} --no-sdist --skip-existing -m Cargo.toml

  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        target: [x86_64]  # aarch64
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build Wheels
        uses: PyO3/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        with:
          command: publish
          target: ${{ matrix.target }}
          args: --no-default-features -i ${{ matrix.python-version }} --no-sdist --skip-existing -m Cargo.toml

  macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        target: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build Wheels
        uses: PyO3/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        with:
          command: publish
          target: ${{ matrix.target }}
          args: -i ${{ matrix.python-version }} --no-sdist --skip-existing -m Cargo.toml
