name: Release 📦

on:
  push:
    tags:
      - "v*.*.*" # Triggers workflow only when a tag matching this pattern is pushed

jobs:
  build-and-publish:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: "Install uv"
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        run: uv python install 3.11

      - name: "Build"
        run: uv build

      - name: "Publish to Test PyPi"
        env:
          TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: uv publish --publish-url https://test.pypi.org/legacy/ --token $TEST_PYPI_TOKEN

      - name: "Verify Test PyPI installation"
        run: |
          uv run -- pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple litebook==$(uv python -c "import litebook; print(litebook.__version__)")
          uv run -- python -c "import litebook; print('Package imported successfully from Test PyPI')"

      - name: "Publish to PyPI"
        if: ${{ success() }}
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: uv publish --token $PYPI_TOKEN
